[package]
name = "newtons_fractal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18"
rand = "0.8"
num = "0.4"
rayon = "1.5"
